### ISSUE TITLE
Quotes - question

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#48]
Just a question - is it a standard behavior? This is not a bug report because I am not sure...

If you quick quote the text which is formatted, the text in quote is changed after you post a reply...

For example:
1) quick quote this part of text in bold (quick reply)
![image](https://user-images.githubusercontent.com/778890/104357387-673e3d00-550d-11eb-8cea-efb1a61dc8cd.png)

2) post this reply

3) check the output - it is not bold anymore... is it fine?

![image](https://user-images.githubusercontent.com/778890/104357456-8210b180-550d-11eb-95ac-28695dae87a8.png)

**Comment by martec** [comment]
Hi,

You are absolutely certain that this does not work correctly. That's because the feature looks for the children node https://github.com/martec/quickadveditorplus/blob/master/jscripts/Thread.quickquote.js#L223 . Chilldren node of your selection is text. Unfortunately I don't have a solution for this. Search for the parent node, I think it will create more bugs than fix.
Anyway, if you select text with different styles, it will work.

@lairdshaw sorry to mention here, if you have a suggestion to fix this i would be very grateful. But I think it is something that is not worth the effort, because I think I would have to rewrite a lot.

**Comment by lairdshaw** [comment]
I agree, @martec. It seems doubtful that there even is a solution to this problem, but if there is, it would be excessively challenging to research and then implement.

**Comment by martec** [comment]
@lairdshaw Thanks for the comment. Yes, it would be quite complicated, so much so that I am even curious as to how this works in the paid system like xenforo.

@Eldenroot yes you are right that this is a bug. Unfortunately, I would not have enough skill to resolve this. So this will be unresolved unfortunately.

**Comment by lairdshaw** [comment]
> I am even curious as to how this works in the paid system like xenforo.

Well, that's a challenge if ever I saw one. We can't be outdone by the XenForo developers, now can we?

So, I've come up with what seems to be a solution, but it needs a lot of testing. It's a revision of the quickadveditorplus/jscripts/Thread.quickquote.js file, because I don't use Rin Editor. I'll submit a PR to the quickadveditorplus repository.

**Comment by lairdshaw** [comment]
Here's that PR:

https://github.com/martec/quickadveditorplus/pull/22

**Comment by martec** [comment]
> Well, that's a challenge if ever I saw one. We can't be outdone by the XenForo developers, now can we?

I checked in XenForo community in test folder... and XenForo has same issue... I thought that in a paid system something like this would work perfectly.

> So, I've come up with what seems to be a solution, but it needs a lot of testing. It's a revision of the quickadveditorplus/jscripts/Thread.quickquote.js file, because I don't use Rin Editor. I'll submit a PR to the quickadveditorplus repository.

thank you very much, i will do some tests here locally.  👍
